// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MAUI_AI_Assistant
{
    internal sealed partial class Vsix
    {
        public const string Id = "MAUI_AI_Assistant.a3e14c43-c8e1-4ec4-b59f-5ef1a9b77999";
        public const string Name = "MAUI_AI_Assistant";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Javier Suárez Ruiz";
        public const string Tags = "";
    }
}
