// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace MAUI_AI_Assistant
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MAUI_AI_AssistantString = "06ff2d61-0d16-486b-aa7e-b980f603edf8";
        public static Guid MAUI_AI_Assistant = new Guid(MAUI_AI_AssistantString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Explain = 0x0100;
        public const int Comment = 0x0200; 
        public const int Suggestion = 0x0300;
        public const int CreateUITest = 0x0400; 
        public const int ConvertFromXamarinForms = 0x0500;
        public const int CustomCommand = 0x0600;
        public const int IconBuilder = 0x0700; 
        public const int ImageCreator = 0x0800; 
        public const int DesignToCode = 0x0900;
    }
}